package com.example.taskzz.ui.theme

import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

//val Purple80 = Color(0xFFD0BCFF)
//val PurpleGrey80 = Color(0xFFCCC2DC)
//val Pink80 = Color(0xFFEFB8C8)
//
//
//val PrimaryBlue = Color(0xFF0A3751)
//val SecondaryOrange = Color(0xFFFC8138)
//val BackgroundBlue = Color(0xFFF4F4F8)
//val OnBackgroundBlack = Color(0xFF282828)
val light_primary = Color(0xFF006495)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFc9e6ff)
val light_onPrimaryContainer = Color(0xFF001e31)
val light_secondary = Color(0xFF50606e)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFd3e4f5)
val light_onSecondaryContainer = Color(0xFF0c1d29)
val light_tertiary = Color(0xFF65587b)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFecdcff)
val light_onTertiaryContainer = Color(0xFF211634)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFfcfcff)
val light_onBackground = Color(0xFF1a1c1e)
val light_surface = Color(0xFFfcfcff)
val light_onSurface = Color(0xFF1a1c1e)
val light_surfaceVariant = Color(0xFFdee3ea)
val light_onSurfaceVariant = Color(0xFF41474d)
val light_outline = Color(0xFF72787e)
val light_inverseOnSurface = Color(0xFFf0f0f3)
val light_inverseSurface = Color(0xFF2f3032)

val dark_primary = Color(0xFF8bcdff)
val dark_onPrimary = Color(0xFF003450)
val dark_primaryContainer = Color(0xFF004b72)
val dark_onPrimaryContainer = Color(0xFFc9e6ff)
val dark_secondary = Color(0xFFb7c8d9)
val dark_onSecondary = Color(0xFF22323f)
val dark_secondaryContainer = Color(0xFF394956)
val dark_onSecondaryContainer = Color(0xFFd3e4f5)
val dark_tertiary = Color(0xFFd0c0e8)
val dark_onTertiary = Color(0xFF362b4a)
val dark_tertiaryContainer = Color(0xFF4d4162)
val dark_onTertiaryContainer = Color(0xFFecdcff)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF1a1c1e)
val dark_onBackground = Color(0xFFe2e2e5)
val dark_surface = Color(0xFF1a1c1e)
val dark_onSurface = Color(0xFFe2e2e5)
val dark_surfaceVariant = Color(0xFF41474d)
val dark_onSurfaceVariant = Color(0xFFc2c7ce)
val dark_outline = Color(0xFF8b9198)
val dark_inverseOnSurface = Color(0xFF1a1c1e)
val dark_inverseSurface = Color(0xFFe2e2e5)

val seed = Color(0xFF0f3750)
val error = Color(0xFFba1b1b)

